# Generated by Django 6.0.6 on 2026-06-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Past', 'Past'), ('On Going', 'On Going'), ('Upcoming', 'Upcoming')], max_length=20)),
                ('banner_img', models.ImageField(upload_to='projects/')),
                ('project_name', models.CharField(max_length=100)),
                ('project_state', models.CharField(max_length=100)),
                ('project_desc', models.TextField()),
                ('property_ownership', models.CharField(choices=[('Freehold', 'Freehold'), ('Leasehold', 'Leasehold')], max_length=20)),
                ('special_features', models.TextField()),
                ('total_units', models.IntegerField()),
                ('floorplan_img', models.ImageField(upload_to='projects/floorplans/')),
                ('gallery_img', models.ImageField(upload_to='projects/gallery/')),
                ('brochure_location', models.ImageField(upload_to='projects/brochures_location/')),
                ('brochure', models.FileField(upload_to='projects/brochures/')),
            ],
        ),
    ]
