# Generated by Django 6.0.6 on 2026-06-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='city',
            field=models.CharField(default='KUALA_LUMPUR', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='progress_tag',
            field=models.CharField(choices=[('Past', 'Past'), ('On Going', 'On Going'), ('Upcoming', 'Upcoming')], default='KUALA_LUMPUR', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_state',
            field=models.CharField(choices=[('PERAK', 'Perak'), ('SELANGOR', 'Selangor'), ('JOHOR', 'Johor'), ('KEDAH', 'Kedah'), ('KELANTAN', 'Kelantan'), ('MELAKA', 'Melaka'), ('PAHANG', 'Pahang'), ('PENANG', 'Pulau Pinang'), ('PERLIS', 'Perlis'), ('TERENGGANU', 'Terengganu'), ('SABAH', 'Sabah'), ('SARAWAK', 'Sarawak'), ('NEGERI_SEMBILAN', 'Negeri Sembilan'), ('KUALA_LUMPUR', 'Kuala Lumpur'), ('LABUAN', 'Labuan'), ('PUTRAJAYA', 'Putrajaya')], max_length=50),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Hide', 'Hide')], max_length=20),
        ),
    ]
