# Generated by Django 6.0.6 on 2026-06-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_projects_city_projects_progress_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='projects/brochures/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='brochure_location',
            field=models.ImageField(blank=True, null=True, upload_to='projects/brochures_location/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='floorplan_img',
            field=models.ImageField(blank=True, null=True, upload_to='projects/floorplans/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='gallery_img',
            field=models.ImageField(blank=True, null=True, upload_to='projects/gallery/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_state',
            field=models.CharField(choices=[('Perak', 'Perak'), ('Selangor', 'Selangor'), ('Johor', 'Johor'), ('Kedah', 'Kedah'), ('Kelantan', 'Kelantan'), ('Melaka', 'Melaka'), ('Pahang', 'Pahang'), ('Pulau Pinang', 'Pulau Pinang'), ('Perlis', 'Perlis'), ('Terengganu', 'Terengganu'), ('Sabah', 'Sabah'), ('Sarawak', 'Sarawak'), ('Negeri Sembilan', 'Negeri Sembilan'), ('Kuala Lumpur', 'Kuala Lumpur'), ('Labuan', 'Labuan'), ('Putrajaya', 'Putrajaya')], max_length=50),
        ),
    ]
