# Generated by Django 6.0.6 on 2026-06-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_projects_brochure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='google_maps_link',
            field=models.URLField(blank=True, help_text='Paste Google Maps link here', null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='waze_link',
            field=models.URLField(blank=True, help_text='Paste Waze link here', null=True),
        ),
    ]
